name: gravyflow2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - scipy
  - gwdatafind
  - gwpy
  - python-lalframe
  - bokeh
  - pycbc
  - pytest
  - sqlalchemy
  - ipykernel
  - python-prctl
  - psycopg2
  - h5py
  - astropy
  - pip:
      - tensorflow[and-cuda]==2.14.*
      - tensorflow-probability==0.22.*
