name: gravyflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8.0
  - gwdatafind
  - gwpy
  - python-lalframe
  - bokeh
  - pycbc
  - pip:
      - nvidia-cudnn-cu11==8.6.0.163
      - tensorflow==2.12.*
      - tensorflow-probability==0.20.*
      - pytest