name: gravyflow_cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - gwdatafind
  - gwpy
  - python-lalframe
  - bokeh
  - pycbc
  - pytest
  - sqlalchemy
  - ipykernel
  - python-prctl
  - tensorflow-cpu==2.12.*

  - pip:
      - tensorflow-probability==0.20.*